[project]
name = "vikunja-discord-reminder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-webhook>=1.4.1",
    "fastapi[standard]>=0.141.1",
    "html-to-markdown>=3.10.2",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
]
